### ISSUE TITLE
Ajax support generates two/three petitions to the API instead of one.

### ISSUE THREAD

**Issue by mateosss** [iamisti/mdDataTable#171]
This is the codepen of the ajax support table:
http://codepen.io/iamisti/pen/BjpNow

If you put a console.log() right above of the $http.post, you will note that it gets printed twice, so the post petition is being executed twice too.

In the search ajax support codepen:
http://codepen.io/iamisti/pen/RRrjLk

It gets executed three times. This cause lots of useless calls, and it is a waste of bandwith.

**Comment by iamisti** [comment]
Hi @mateosss 
Good catch! Going to fix it with the next release

**Comment by iamisti** [comment]
Initial load has been fixed with v1.6.10, but the search fix will be part only in the next release.

**Comment by theGirlWithTheDragonTattoo** [comment]
Hi, 
I am using version 2.2.0 and still have the problem where the function paginatorCallback() initially been called twice.
